### ISSUE TITLE
[RFE] implement image import support from oVirt Glance

### ISSUE THREAD

**Issue by jekader** [oVirt/ovirt-ansible-manageiq#14]
Currently the disk image is downloaded from the Upstream website to a local directory and is then sent to the oVirt setup through the API, which means that data is sent from the Engine to a Host in background and then to the storage domain. This RFE proposes importing the image from oVirt Glance directly which can decrease the time needed as it will be fetched directly from Glance to the hypervisor, skipping the system where Ansible is run from

**Comment by mwperina** [comment]
Development moved to https://github.com/ovirt/ovirt-ansible-collection If this is still relevant, please reopen there.
