### ISSUE TITLE
RHV Provider existence should be checked by API endpoint

### ISSUE THREAD

**Issue by jekader** [oVirt/ovirt-ansible-manageiq#15]
Currently, the playbook will only check the name of the RHV provider to identify the provider while engine_fqdn must also be unique and the setup will fail if a duplicate is added.

Steps to reproduce:
1) set the miq_rhv_provider_name variable to "oVirt1"
2) run playbook to deploy ManageIQ
3) change miq_rhv_provider_name to "oVirt2" without changing anything else
4) re-run the playbook

Actual result:
Playbook fails with error:
"Could not create the new provider - Validation failed: Host Name has to be unique per provider type"

Expected result:
Playbook skips adding provider as it is already present and completes successfully

**Comment by machacekondra** [comment]
Unfornatelly there is no Ansible module which would manage ManageIQ providers, so let's just ignore the error, and pass. Better would be to change the name.
