### ISSUE TITLE
Create the disk at least the same size as qcow image reports

### ISSUE THREAD

**Issue by jekader** [oVirt/ovirt-ansible-manageiq#18]
The [minimum requirements](https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6-beta/html/deployment_planning_guide/introduction#virtual-hardware-requirements) for ManageIQ on RHV are:
* 4 VCPUs
* 12 GB RAM
* 44 GB HDD + optional database disk

In fact, the qcow image size for manageiq-ovirt-gaprindashvili-1.qc2 is 66GB form qemu-img info

These values should be set in [defaults/main.yaml](https://github.com/oVirt/ovirt-ansible-manageiq/blob/master/defaults/main.yml). Ideally, the size of the downloaded QCOW should be verified on the spot and set as the minimum. Creating a 50GB disk for a 66GB QCOW can and will lead to data corruption once data starts filling the disk.

**Comment by machacekondra** [comment]
Fixed defaults values, but leaving open for doing a check on the qcow image.

**Comment by machacekondra** [comment]
We can calculate the size same as here:

 https://github.com/oVirt/ovirt-ansible-image-template/blob/master/tasks/qcow2_image.yml#L25
