### ISSUE TITLE
miq_password is not applied during deploy

### ISSUE THREAD

**Issue by jekader** [oVirt/ovirt-ansible-manageiq#21]
When a custom miq_password is defined, it is not applied during deploy. ManageIQ starts with the default password which blocks the playbook and is insecure in general.

Reproduceable with manageiq-ovirt-gaprindashvili-1.qc2 and ovirt-ansible-manageiq-1.1.6-0.1.master.20180209141024.el7.centos.noarch

**Comment by machacekondra** [comment]
`miq_password` is used actually as password to login to API, not to be set it to anything. To set root password on VM there is `cloud_init` option to do so.

**Comment by jekader** [comment]
ManageIQ supplies a very well known admin password and this playbook effectively deploys and starts a service that is reachable by external users. Theoretically, anyone can access the instance at this point which is a security issue and should be fixed.

Looking at how this is done on the appliance side, we should be able to interject using cloud-init to override the password before ManageIQ starts for the first time:
https://github.com/ManageIQ/manageiq-appliance-build/blob/master/kickstarts/partials/post/db_init.ks.erb
