### ISSUE TITLE
[RFE] enable C&U gathering when metrics are configured

### ISSUE THREAD

**Issue by jekader** [oVirt/ovirt-ansible-manageiq#22]
The playbook can set up C&U connectivity when adding the RHV provider, however this is useless unless C&U roles are enabled on the instance and C&U gathering is activated. It would be great if the playbook could do this, maybe in an optional manner as this consumes a lot of resources.

**Comment by mwperina** [comment]
Development moved to https://github.com/ovirt/ovirt-ansible-collection If this is still relevant, please reopen there.
