### ISSUE TITLE
Use manageiq_provider module when Ansible 2.5 is out

### ISSUE THREAD

**Issue by machacekondra** [oVirt/ovirt-ansible-manageiq#24]
https://github.com/ansible/ansible/commit/ebd096a732cb4c6ebd2b13c063a449579381a2f7#diff-d282374f7f4e8ce8c63becb85a3130b4

**Comment by ghost** [comment]
`manageiq_provider` module depends on `manageiq_client` Python module, which is not shipped with oVirt, nor exist as a RPM.
