### ISSUE TITLE
VM hostname is not set via cloud-init

### ISSUE THREAD

**Issue by mykaul** [oVirt/ovirt-ansible-manageiq#48]
The VM hostname remains localhost, as it is not set by cloud-init.
I'm not sure if it's a RFE or bug (since we do not ask or set the IP as well), but since we do have a VM name, I expect it to be set as the host name as well.

**Comment by mykaul** [comment]
Could be a cloud-init bug. Need to re-test with CentOS 7.5 / RHEL 7.5

**Comment by machacekondra** [comment]
Yes, it is cloud-init bug, works fine with el7.5
