### ISSUE TITLE
upgraded RHEVM 3.x to latest 4.x has network rhevm instead of ovirtmgmt

### ISSUE THREAD

**Issue by pkubica** [oVirt/ovirt-ansible-manageiq#78]
I think that role should work also with upgraded environment from RHEVM 3.x by default. After upgrade to 4.3  the name of the network is still rhevm.
This will cause that roles will not work by default on these environments and it is necessary to always set variable to specify network and profile.
From my point of view, it would be better to check if ovirtmgmt/rhevm exists on target environment and set the default of the network appropriately.

**Comment by mwperina** [comment]
Dominik, I thought we have already moved to ovirtmgmt even on downstream. Or I missing something?

@dominikholler

**Comment by mwperina** [comment]
Development moved to https://github.com/ovirt/ovirt-ansible-collection If this is still relevant, please reopen there.
