### ISSUE TITLE
Can't deploy CFME

### ISSUE THREAD

**Issue by pkubica** [oVirt/ovirt-ansible-manageiq#82]
TASK [oVirt.manageiq : Set root password of appliance] *****************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Shared connection to xx.xx.xx.xx closed.\r\n", "module_stdout": "/bin/sh: /usr/bin/python: No such file or directory\r\n", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127}

version of cfme:
cfme-rhevm-5.11.0.5-1.x86_64.qcow2

cfme appliance:
ls /usr/bin/ | grep pyth
python2
python2.7
python3
python3.6
python3.6m
unversioned-python

**Comment by machacekondra** [comment]
To simple solve the issue just change `ansible_python_interpreter` variable to proper path.

**Comment by pkubica** [comment]
it works with that and then it should be documented that from CFME 5.xy is necessary to set that variable (ansible_python_interpreter).
Or is this issue a CFME bug from Ansible point of view?

**Comment by mwperina** [comment]
Development moved to https://github.com/ovirt/ovirt-ansible-collection If this is still relevant, please reopen there.
