### ISSUE TITLE
Additional created disks aren't activated in oVirt

### ISSUE THREAD

**Issue by pkubica** [oVirt/ovirt-ansible-manageiq#84]
Additional disk such as database, logs, tmp.. aren't activated.
role will fail on waiting for API:
FAILED - RETRYING: Wait for ManageIQ/CloudForms API (1 retries left).

**Comment by mwperina** [comment]
Development moved to https://github.com/ovirt/ovirt-ansible-collection If this is still relevant, please reopen there.
