### ISSUE TITLE
Latest RHEL/CentOS 8 based ManageIQ does not contain `/usr/bin/python`

### ISSUE THREAD

**Issue by kedark3** [oVirt/ovirt-ansible-manageiq#91]
As of latest ManageIQ nightly, I observed that there is no `/usr/bin/python` on the appliances, and hence the execution fails as follows: 
```
TASK [ovirt.manageiq : Start ManageIQ server] **********************************
task path: /tmp/awx_30537_j5qzarka/project/tasks/init_cfme.yml:26
fatal: [localhost -> 10.8.197.124]: FAILED! => {"changed": false, "module_stderr": "Shared 
connection to 10.8.197.124 closed.\r\n", "module_stdout": "/bin/sh: /usr/bin/python: No such file or 
directory\r\n", "msg": "The module failed to execute correctly, you probably need to set the 
interpreter.\nSee stdout/stderr for the exact error", "rc": 127}
```

I did see `/usr/bin/python3` on there, so I think we need to update this role ovirt-ansible-manageiq to handle that smartly.

**Comment by mwperina** [comment]
Development moved to https://github.com/ovirt/ovirt-ansible-collection If this is still relevant, please reopen there.
